#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""adc-midi-split.py 260801f

Split selected drum-pattern ranges from an original MIDI file according to an
ADC PatternLab CSV, and/or create an A4 portrait 2-column x 5-row PDF catalog.

Inputs
------
1. Original MIDI file (SMF Type 0 or 1)
2. PatternLab CSV generated by adc-patternlab.py
3. slot_map_definitions.json (default: beside this script)

Outputs are selected independently:
    --split   Save one CH10 MIDI file per EXPORT=YES row.
    --pdf     Create a multi-page pattern-grid PDF for EXPORT=YES rows.

The script performs no genre, subdivision, name, duplicate, or slot-map
inference. Those decisions are taken directly from the reviewed CSV.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Set, Tuple

import mido
from mido import Message, MetaMessage, MidiFile, MidiTrack

from adc_rhythm_analysis import detect_flams

SCRIPT_NAME = "adc-midi-split.py"
VERSION = "260802a"
VERSION_TEXT = f"{SCRIPT_NAME} {VERSION}"

REQUIRED_COLUMNS = {
    "FILE",
    "START_BAR",
    "END_BAR",
    "NAME",
    "TIME_SIG",
    "SLOT_MAP",
    "EXPORT",
    "SUBDIV",
    "SOURCE",
}
VALID_SUBDIV = {"16", "8T", "16T"}
NAME_RE = re.compile(r"^[A-Z0-9]{3}_[0-9]{4}$")

# PDF accent palette. Empty cells remain white.
PDF_ACCENT_COLORS = {
    1: (70, 130, 255),   # soft: blue
    2: (55, 170, 95),    # normal: green
    3: (220, 55, 55),    # accent: red
}
PDF_VELOCITY_THRESHOLDS = (64, 96)

try:
    from PIL import Image, ImageDraw, ImageFont  # type: ignore

    PIL_AVAILABLE = True
except ImportError:
    PIL_AVAILABLE = False


@dataclass(frozen=True)
class SlotDefinition:
    index: int
    abbrev: str
    extended: str
    representative_midi: int
    allowed_notes: Tuple[int, ...]


@dataclass(frozen=True)
class SlotMapDefinition:
    map_id: int
    name: str
    slots: Tuple[SlotDefinition, ...]

    @property
    def accepted_notes(self) -> Set[int]:
        out: Set[int] = set()
        for slot in self.slots:
            out.update(slot.allowed_notes)
        return out

    def slot_for_note(self, note: int) -> Optional[int]:
        for slot in self.slots:
            if note in slot.allowed_notes:
                return slot.index
        return None


@dataclass(frozen=True)
class PatternSpec:
    row_number: int
    file: str
    start_bar: int
    end_bar: int
    name: str
    time_sig: str
    slot_map: str
    export: bool
    genre: str
    subdiv: str
    orn: bool
    duplicate_of: str
    source: str


@dataclass(frozen=True)
class BarInfo:
    number: int
    start_tick: int
    end_tick: int
    numerator: int
    denominator: int


@dataclass(frozen=True)
class AbsoluteEvent:
    tick: int
    order: int
    message: Message | MetaMessage


# ---------------------------------------------------------------------------
# Generic helpers
# ---------------------------------------------------------------------------


def fail(message: str) -> "NoReturn":
    raise SystemExit(f"[ERROR] {message}")


def parse_yes_no(value: str, *, field: str, row_number: int) -> bool:
    normalized = value.strip().upper()
    if normalized == "YES":
        return True
    if normalized == "NO":
        return False
    fail(f"CSV row {row_number}: {field} must be YES or NO, got {value!r}")


def parse_time_signature(value: str, *, row_number: int) -> Tuple[int, int]:
    m = re.fullmatch(r"([1-9][0-9]*)/([1-9][0-9]*)", value.strip())
    if not m:
        fail(f"CSV row {row_number}: invalid TIME_SIG {value!r}")
    num, den = int(m.group(1)), int(m.group(2))
    if den & (den - 1):
        fail(f"CSV row {row_number}: TIME_SIG denominator must be a power of two: {value!r}")
    return num, den


def safe_output_stem(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", name).strip("._") or "patterns"


def choose_font(size: int, bold: bool = False):
    if not PIL_AVAILABLE:
        return None
    candidates = []
    if sys.platform.startswith("win"):
        candidates.extend(
            [
                r"C:\Windows\Fonts\arialbd.ttf" if bold else r"C:\Windows\Fonts\arial.ttf",
                r"C:\Windows\Fonts\calibrib.ttf" if bold else r"C:\Windows\Fonts\calibri.ttf",
            ]
        )
    candidates.extend(
        [
            "DejaVuSans-Bold.ttf" if bold else "DejaVuSans.ttf",
            "Arial Bold.ttf" if bold else "Arial.ttf",
        ]
    )
    for candidate in candidates:
        try:
            return ImageFont.truetype(candidate, size)
        except Exception:
            continue
    return ImageFont.load_default()


# ---------------------------------------------------------------------------
# Slot-map JSON
# ---------------------------------------------------------------------------


def load_slot_maps(path: Path) -> Dict[str, SlotMapDefinition]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        fail(f"slot-map definition not found: {path}")
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"cannot read slot-map definition {path}: {exc}")

    if not isinstance(data, list) or not data:
        fail("slot-map JSON root must be a non-empty array")

    maps: Dict[str, SlotMapDefinition] = {}
    ids: Set[int] = set()
    for item in data:
        if not isinstance(item, dict):
            fail("each slot-map JSON entry must be an object")
        map_id = item.get("slot_map_id")
        name = item.get("name")
        slots_data = item.get("slots")
        if not isinstance(map_id, int) or map_id in ids:
            fail(f"invalid or duplicate slot_map_id: {map_id!r}")
        if not isinstance(name, str) or not name.strip() or name in maps:
            fail(f"invalid or duplicate slot-map name: {name!r}")
        if not isinstance(slots_data, list) or not slots_data:
            fail(f"slot map {name}: slots must be a non-empty list")

        parsed_slots: List[SlotDefinition] = []
        seen_indices: Set[int] = set()
        for raw in slots_data:
            if not isinstance(raw, dict):
                fail(f"slot map {name}: every slot must be an object")
            index = raw.get("slot")
            abbrev = raw.get("abbrev")
            extended = raw.get("extended", abbrev)
            representative = raw.get("representative_midi")
            allowed = raw.get("midi_input_allowed")
            if not isinstance(index, int) or index in seen_indices:
                fail(f"slot map {name}: invalid or duplicate slot number {index!r}")
            if not isinstance(abbrev, str) or not abbrev.strip():
                fail(f"slot map {name}, slot {index}: missing abbrev")
            if not isinstance(extended, str) or not extended.strip():
                fail(f"slot map {name}, slot {index}: missing extended name")
            if not isinstance(representative, int):
                fail(f"slot map {name}, slot {index}: invalid representative_midi")
            if not isinstance(allowed, list) or not allowed or any(not isinstance(n, int) for n in allowed):
                fail(f"slot map {name}, slot {index}: invalid midi_input_allowed")
            if representative not in allowed:
                fail(f"slot map {name}, slot {index}: representative_midi must be allowed")
            seen_indices.add(index)
            parsed_slots.append(
                SlotDefinition(
                    index=index,
                    abbrev=abbrev.strip(),
                    extended=extended.strip(),
                    representative_midi=representative,
                    allowed_notes=tuple(allowed),
                )
            )

        parsed_slots.sort(key=lambda slot: slot.index)
        expected = list(range(len(parsed_slots)))
        actual = [slot.index for slot in parsed_slots]
        if actual != expected:
            fail(f"slot map {name}: slot numbers must be contiguous 0..{len(parsed_slots)-1}")

        ids.add(map_id)
        maps[name] = SlotMapDefinition(map_id, name, tuple(parsed_slots))

    return maps


# ---------------------------------------------------------------------------
# PatternLab CSV
# ---------------------------------------------------------------------------


def load_pattern_csv(path: Path) -> List[PatternSpec]:
    try:
        handle = path.open("r", encoding="utf-8-sig", newline="")
    except OSError as exc:
        fail(f"cannot open CSV {path}: {exc}")

    with handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None:
            fail(f"CSV has no header: {path}")
        normalized_fields = [str(field).strip().upper() for field in reader.fieldnames]
        missing = sorted(REQUIRED_COLUMNS - set(normalized_fields))
        if missing:
            fail(f"CSV missing required column(s): {', '.join(missing)}")
        reader.fieldnames = normalized_fields

        specs: List[PatternSpec] = []
        for row_number, raw in enumerate(reader, start=2):
            if raw is None or not any(str(v or "").strip() for v in raw.values()):
                continue
            row = {str(k).strip().upper(): str(v or "").strip() for k, v in raw.items() if k is not None}
            try:
                start_bar = int(row.get("START_BAR", ""))
                end_bar = int(row.get("END_BAR", ""))
            except ValueError:
                fail(f"CSV row {row_number}: START_BAR and END_BAR must be integers")
            if start_bar < 1 or end_bar < start_bar:
                fail(f"CSV row {row_number}: invalid bar range {start_bar}-{end_bar}")

            export = parse_yes_no(row.get("EXPORT", ""), field="EXPORT", row_number=row_number)

            name = row.get("NAME", "").upper()
            if export:
                if not NAME_RE.fullmatch(name):
                    fail(
                        f"CSV row {row_number}: NAME must match ABC_0001 "
                        f"for EXPORT=YES, got {name!r}"
                    )
            elif name and not NAME_RE.fullmatch(name):
                fail(
                    f"CSV row {row_number}: non-empty NAME must match ABC_0001, "
                    f"got {name!r}"
                )

            time_sig = row.get("TIME_SIG", "")
            parse_time_signature(time_sig, row_number=row_number)

            subdiv = row.get("SUBDIV", "").upper()
            if subdiv not in VALID_SUBDIV:
                fail(f"CSV row {row_number}: SUBDIV must be one of 16, 8T, 16T, got {subdiv!r}")

            orn_raw = row.get("ORN", "NO") or "NO"
            orn = parse_yes_no(orn_raw, field="ORN", row_number=row_number)

            specs.append(
                PatternSpec(
                    row_number=row_number,
                    file=row.get("FILE", ""),
                    start_bar=start_bar,
                    end_bar=end_bar,
                    name=name,
                    time_sig=time_sig,
                    slot_map=row.get("SLOT_MAP", ""),
                    export=export,
                    genre=row.get("GENRE", "").upper(),
                    subdiv=subdiv,
                    orn=orn,
                    duplicate_of=row.get("DUPLICATE_OF", ""),
                    source=row.get("SOURCE", ""),
                )
            )

    if not specs:
        fail("CSV contains no pattern rows")
    return specs


# ---------------------------------------------------------------------------
# MIDI reading and bar map
# ---------------------------------------------------------------------------


def merged_absolute_events(mid: MidiFile) -> List[AbsoluteEvent]:
    merged = mido.merge_tracks(mid.tracks) if mid.type == 1 else mid.tracks[0]
    events: List[AbsoluteEvent] = []
    tick = 0
    for order, msg in enumerate(merged):
        tick += msg.time
        events.append(AbsoluteEvent(tick, order, msg.copy(time=0)))
    return events


def collect_time_signatures(events: Sequence[AbsoluteEvent]) -> List[Tuple[int, int, int]]:
    values: Dict[int, Tuple[int, int]] = {0: (4, 4)}
    for event in events:
        msg = event.message
        if isinstance(msg, MetaMessage) and msg.type == "time_signature":
            values[event.tick] = (int(msg.numerator), int(msg.denominator))
    return [(tick, num, den) for tick, (num, den) in sorted(values.items())]


def build_bar_map(tpq: int, time_signatures: Sequence[Tuple[int, int, int]], total_tick: int) -> List[BarInfo]:
    if tpq <= 0:
        fail(f"invalid ticks_per_beat: {tpq}")
    if total_tick <= 0:
        fail("MIDI contains no timed content")

    bars: List[BarInfo] = []
    ts_index = 0
    tick = 0
    number = 1
    while tick < total_tick:
        while ts_index + 1 < len(time_signatures) and time_signatures[ts_index + 1][0] <= tick:
            ts_index += 1
        _, num, den = time_signatures[ts_index]
        nominal_end = tick + max(1, round(tpq * num * 4 / den))
        if ts_index + 1 < len(time_signatures):
            next_change = time_signatures[ts_index + 1][0]
            if tick < next_change < nominal_end:
                nominal_end = next_change
        bars.append(BarInfo(number, tick, nominal_end, num, den))
        tick = nominal_end
        number += 1
    return bars


def active_meta_before(events: Sequence[AbsoluteEvent], start_tick: int) -> Tuple[Tuple[int, int], int]:
    time_sig = (4, 4)
    tempo = 500000
    for event in events:
        if event.tick > start_tick:
            break
        msg = event.message
        if isinstance(msg, MetaMessage):
            if msg.type == "time_signature":
                time_sig = (int(msg.numerator), int(msg.denominator))
            elif msg.type == "set_tempo":
                tempo = int(msg.tempo)
    return time_sig, tempo


def drum_note_ons(events: Sequence[AbsoluteEvent], start_tick: int, end_tick: int) -> List[AbsoluteEvent]:
    return [
        event
        for event in events
        if start_tick <= event.tick < end_tick
        and isinstance(event.message, Message)
        and getattr(event.message, "channel", -1) == 9
        and event.message.type == "note_on"
        and event.message.velocity > 0
    ]


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def validate_specs(
    specs: Sequence[PatternSpec],
    input_midi: Path,
    slot_maps: Dict[str, SlotMapDefinition],
    bars: Sequence[BarInfo],
    events: Sequence[AbsoluteEvent],
) -> List[PatternSpec]:
    selected = [spec for spec in specs if spec.export]
    if not selected:
        fail("CSV has no EXPORT=YES rows")

    names: Set[str] = set()
    expected_file = input_midi.name.casefold()
    for spec in selected:
        if Path(spec.file).name.casefold() != expected_file:
            fail(
                f"CSV row {spec.row_number}: FILE={spec.file!r} does not match input MIDI {input_midi.name!r}"
            )
        if spec.name in names:
            fail(f"CSV row {spec.row_number}: duplicate NAME {spec.name}")
        names.add(spec.name)
        if spec.slot_map not in slot_maps:
            fail(f"CSV row {spec.row_number}: unknown SLOT_MAP {spec.slot_map!r}")
        if spec.end_bar > len(bars):
            fail(
                f"CSV row {spec.row_number}: bar range {spec.start_bar}-{spec.end_bar} exceeds MIDI bar count {len(bars)}"
            )
        start_bar = bars[spec.start_bar - 1]
        end_bar = bars[spec.end_bar - 1]
        actual_ts_values = {(bar.numerator, bar.denominator) for bar in bars[spec.start_bar - 1 : spec.end_bar]}
        csv_ts = parse_time_signature(spec.time_sig, row_number=spec.row_number)
        if len(actual_ts_values) != 1 or csv_ts not in actual_ts_values:
            actual_text = "→".join(f"{bar.numerator}/{bar.denominator}" for bar in bars[spec.start_bar - 1 : spec.end_bar])
            fail(
                f"CSV row {spec.row_number}: TIME_SIG={spec.time_sig} does not match bars {spec.start_bar}-{spec.end_bar} ({actual_text})"
            )
        expected_source = f"{input_midi.name}:{spec.start_bar}-{spec.end_bar}"
        if spec.source != expected_source:
            fail(
                f"CSV row {spec.row_number}: SOURCE={spec.source!r}; expected {expected_source!r}"
            )
        hits = drum_note_ons(events, start_bar.start_tick, end_bar.end_tick)
        if not hits:
            fail(f"CSV row {spec.row_number}: no CH10 drum note_on events in selected range")
        notes = {int(event.message.note) for event in hits if isinstance(event.message, Message)}
        missing = sorted(notes - slot_maps[spec.slot_map].accepted_notes)
        if missing:
            fail(
                f"CSV row {spec.row_number}: SLOT_MAP {spec.slot_map} does not accept MIDI note(s) {missing}"
            )

    return selected


# ---------------------------------------------------------------------------
# MIDI splitting
# ---------------------------------------------------------------------------


def extract_segment_messages(
    events: Sequence[AbsoluteEvent],
    start_tick: int,
    end_tick: int,
) -> List[Tuple[int, int, Message | MetaMessage]]:
    segment: List[Tuple[int, int, Message | MetaMessage]] = []
    time_sig, tempo = active_meta_before(events, start_tick)
    segment.append((0, -20, MetaMessage("time_signature", numerator=time_sig[0], denominator=time_sig[1], time=0)))
    segment.append((0, -19, MetaMessage("set_tempo", tempo=tempo, time=0)))

    for event in events:
        if event.tick < start_tick:
            continue
        if event.tick >= end_tick:
            break
        msg = event.message
        relative = event.tick - start_tick
        if isinstance(msg, Message) and getattr(msg, "channel", -1) == 9 and msg.type in {"note_on", "note_off"}:
            segment.append((relative, event.order, msg.copy(time=0)))
        elif isinstance(msg, MetaMessage) and msg.type in {"set_tempo", "time_signature"}:
            if relative == 0:
                continue
            segment.append((relative, event.order, msg.copy(time=0)))

    # Guarantee note-offs for any notes still active at the segment boundary.
    active: Dict[int, int] = {}
    for tick, _, msg in sorted(segment, key=lambda item: (item[0], item[1])):
        if not isinstance(msg, Message) or getattr(msg, "channel", -1) != 9:
            continue
        if msg.type == "note_on" and msg.velocity > 0:
            active[msg.note] = active.get(msg.note, 0) + 1
        elif msg.type == "note_off" or (msg.type == "note_on" and msg.velocity == 0):
            if active.get(msg.note, 0) > 0:
                active[msg.note] -= 1
    close_tick = max(0, end_tick - start_tick - 1)
    order = 10**9
    for note, count in sorted(active.items()):
        for _ in range(count):
            segment.append((close_tick, order, Message("note_off", channel=9, note=note, velocity=0, time=0)))
            order += 1

    return sorted(segment, key=lambda item: (item[0], item[1]))


def save_segment_midi(
    spec: PatternSpec,
    output_path: Path,
    mid: MidiFile,
    bars: Sequence[BarInfo],
    events: Sequence[AbsoluteEvent],
) -> None:
    start_tick = bars[spec.start_bar - 1].start_tick
    end_tick = bars[spec.end_bar - 1].end_tick
    messages = extract_segment_messages(events, start_tick, end_tick)

    out = MidiFile(type=0, ticks_per_beat=mid.ticks_per_beat)
    track = MidiTrack()
    out.tracks.append(track)

    last_tick = 0
    for absolute_tick, _, msg in messages:
        delta = absolute_tick - last_tick
        if delta < 0:
            fail(f"internal error while writing {spec.name}: negative delta time")
        last_tick = absolute_tick
        track.append(msg.copy(time=delta))
    segment_length = end_tick - start_tick
    track.append(MetaMessage("end_of_track", time=max(0, segment_length - last_tick)))
    out.save(output_path)


# ---------------------------------------------------------------------------
# PDF rendering (Pillow + optional Ghostscript)
# ---------------------------------------------------------------------------


def find_ghostscript_executable() -> Optional[str]:
    for name in ("gswin64c", "gswin32c", "gs"):
        path = shutil.which(name)
        if path:
            return path
    return None


def convert_pdf_to_a4_with_ghostscript(gs_exe: str, input_pdf: Path, output_pdf: Path) -> bool:
    cmd = [
        gs_exe,
        "-sDEVICE=pdfwrite",
        "-o",
        str(output_pdf),
        "-dDEVICEWIDTHPOINTS=595",
        "-dDEVICEHEIGHTPOINTS=842",
        "-dFIXEDMEDIA",
        "-dPDFFitPage",
        "-dNOPAUSE",
        "-dBATCH",
        str(input_pdf),
    ]
    print("[PDF] Ghostscript A4 resize:")
    print("      " + " ".join(cmd))
    try:
        result = subprocess.run(cmd, check=False)
    except OSError as exc:
        print(f"[WARN] Ghostscript could not be started: {exc}")
        return False
    return result.returncode == 0 and output_pdf.exists()


def steps_for_pattern(spec: PatternSpec, bar_count: int, numerator: int, denominator: int) -> int:
    quarter_notes_per_bar = numerator * 4 / denominator
    cells_per_quarter = {"16": 4, "8T": 3, "16T": 6}[spec.subdiv]
    columns = quarter_notes_per_bar * cells_per_quarter * bar_count
    rounded = round(columns)
    if not math.isclose(columns, rounded, abs_tol=1e-9):
        fail(
            f"CSV row {spec.row_number}: TIME_SIG={spec.time_sig}, SUBDIV={spec.subdiv}, "
            f"and {bar_count} bar(s) do not yield an integer step count"
        )
    return max(1, int(rounded))


def pdf_accent_level(velocity: int) -> int:
    """Map MIDI velocity to the three PDF accent colors."""
    low, high = PDF_VELOCITY_THRESHOLDS
    if velocity < low:
        return 1
    if velocity < high:
        return 2
    return 3


def quantized_slot_cells(
    spec: PatternSpec,
    slot_map: SlotMapDefinition,
    bars: Sequence[BarInfo],
    events: Sequence[AbsoluteEvent],
    tpq: int,
) -> Tuple[int, Dict[Tuple[int, int], int], Set[Tuple[int, int]]]:
    """Return accent levels by cell and flam-main cells for PDF rendering.

    Flam detection is delegated to adc_rhythm_analysis. Only conservative
    HIGH/MEDIUM candidates marked remove_from_subdivision are rendered, and
    only when the reviewed CSV row has ORN=YES.
    """
    first_bar = bars[spec.start_bar - 1]
    last_bar = bars[spec.end_bar - 1]
    start_tick = first_bar.start_tick
    end_tick = last_bar.end_tick
    bar_count = spec.end_bar - spec.start_bar + 1
    columns = steps_for_pattern(spec, bar_count, first_bar.numerator, first_bar.denominator)
    length = end_tick - start_tick

    note_events = drum_note_ons(events, start_tick, end_tick)
    event_cells: List[Optional[Tuple[int, int]]] = []
    rhythm_events = []

    # First establish every event's quantized target and run the same shared
    # flam analysis used by PatternLab and the ADT writer. Do not populate the
    # PDF grid yet: removable grace notes must be excluded before quantization.
    for event in note_events:
        assert isinstance(event.message, Message)
        slot_index = slot_map.slot_for_note(int(event.message.note))
        cell: Optional[Tuple[int, int]] = None
        if slot_index is not None:
            relative = event.tick - start_tick
            col = int(math.floor(relative / max(1, length) * columns + 0.5))
            col = max(0, min(columns - 1, col))
            cell = (slot_index, col)
        event_cells.append(cell)
        rhythm_events.append(
            {
                "tick": event.tick,
                "note": int(event.message.note),
                "velocity": int(event.message.velocity),
                "track": 0,
            }
        )

    excluded_grace_indices: Set[int] = set()
    flam_cells: Set[Tuple[int, int]] = set()
    if spec.orn and rhythm_events:
        flam_analysis = detect_flams(
            rhythm_events,
            tpq=max(1, tpq),
            loop_ticks=length,
            loop_start=start_tick,
        )
        for item in flam_analysis.get("flams", []):
            if not item.get("remove_from_subdivision"):
                continue

            grace_index = item.get("grace_index")
            if isinstance(grace_index, int) and 0 <= grace_index < len(note_events):
                excluded_grace_indices.add(grace_index)

            main_index = item.get("main_index")
            if isinstance(main_index, int) and 0 <= main_index < len(event_cells):
                cell = event_cells[main_index]
                if cell is not None:
                    flam_cells.add(cell)

    # Build the regular ADT/ADP-style PDF grid only from retained main events.
    # A loop-boundary grace note therefore cannot be rounded and clamped into
    # the final cell. Its target main cell receives the white flam marker.
    cells: Dict[Tuple[int, int], int] = {}
    for event_index, event in enumerate(note_events):
        if event_index in excluded_grace_indices:
            continue
        cell = event_cells[event_index]
        if cell is None:
            continue
        assert isinstance(event.message, Message)
        level = pdf_accent_level(int(event.message.velocity))
        cells[cell] = max(level, cells.get(cell, 0))

    return columns, cells, flam_cells


def render_pattern_png(
    spec: PatternSpec,
    slot_map: SlotMapDefinition,
    bars: Sequence[BarInfo],
    events: Sequence[AbsoluteEvent],
    output_path: Path,
    tpq: int,
) -> None:
    if not PIL_AVAILABLE:
        fail("Pillow is required for --pdf (pip install Pillow)")

    first_bar = bars[spec.start_bar - 1]
    bar_count = spec.end_bar - spec.start_bar + 1
    columns, cells, flam_cells = quantized_slot_cells(spec, slot_map, bars, events, tpq)
    row_slots = list(reversed(slot_map.slots))
    rows = len(row_slots)

    cell_w = 10
    cell_h = 10
    left_margin = 44
    right_margin = 8
    top_margin = 32
    bottom_margin = 8
    width = left_margin + columns * cell_w + right_margin
    height = top_margin + rows * cell_h + bottom_margin

    image = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(image)
    title_font = choose_font(15, bold=False)
    label_font = choose_font(10, bold=False)

    title_parts = [spec.name, f"bars {spec.start_bar}-{spec.end_bar}", spec.subdiv, spec.slot_map]
    if spec.orn:
        title_parts.append("ORN")
    title = f"{title_parts[0]} ({', '.join(title_parts[1:])})"
    bbox = draw.textbbox((0, 0), title, font=title_font)
    draw.text(((width - (bbox[2] - bbox[0])) / 2, 5), title, fill="black", font=title_font)

    gx, gy = left_margin, top_margin
    quarter_notes_per_bar = first_bar.numerator * 4 / first_bar.denominator
    cells_per_quarter = {"16": 4, "8T": 3, "16T": 6}[spec.subdiv]
    steps_per_bar = int(round(quarter_notes_per_bar * cells_per_quarter))

    for col in range(columns + 1):
        x = gx + col * cell_w
        is_bar = 0 < col < columns and col % steps_per_bar == 0
        is_beat = col % cells_per_quarter == 0
        if is_bar:
            color, line_width = "black", 3
        elif is_beat:
            color, line_width = (90, 90, 90), 1
        else:
            color, line_width = (220, 220, 220), 1
        draw.line((x, gy, x, gy + rows * cell_h), fill=color, width=line_width)

    for row in range(rows + 1):
        y = gy + row * cell_h
        draw.line((gx, y, gx + columns * cell_w, y), fill=(220, 220, 220), width=1)

    display_row_for_slot: Dict[int, int] = {}
    for display_row, slot in enumerate(row_slots):
        display_row_for_slot[slot.index] = display_row
        draw.text((4, gy + display_row * cell_h), slot.abbrev, fill="black", font=label_font)

    for (slot_index, col), accent_level in sorted(cells.items()):
        row = display_row_for_slot[slot_index]
        x0 = gx + col * cell_w + 1
        y0 = gy + row * cell_h + 1
        x1 = x0 + cell_w - 2
        y1 = y0 + cell_h - 2
        fill_color = PDF_ACCENT_COLORS[accent_level]
        draw.rectangle((x0, y0, x1, y1), fill=fill_color)

        if (slot_index, col) in flam_cells:
            # ORN flam marker: a small white square inside the main note, top-left.
            marker_size = max(2, min(cell_w, cell_h) // 3)
            inset = 1
            mx0 = x0 + inset
            my0 = y0 + inset
            draw.rectangle(
                (mx0, my0, mx0 + marker_size - 1, my0 + marker_size - 1),
                fill="white",
            )

    image.save(output_path)


def create_pdf_catalog(
    specs: Sequence[PatternSpec],
    slot_maps: Dict[str, SlotMapDefinition],
    bars: Sequence[BarInfo],
    events: Sequence[AbsoluteEvent],
    input_midi: Path,
    input_midi_tpq: int,
    final_pdf: Path,
    *,
    keep_png: bool,
    no_ghostscript: bool,
    overwrite: bool,
) -> int:
    if not PIL_AVAILABLE:
        fail("Pillow is required for --pdf (pip install Pillow)")
    if final_pdf.exists() and not overwrite:
        fail(f"PDF already exists: {final_pdf} (use --overwrite)")

    final_pdf.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="adc_midi_split_") as tmp_name:
        tmp_dir = Path(tmp_name)
        png_paths: List[Path] = []
        for spec in specs:
            png_path = tmp_dir / f"{spec.name}_grid.png"
            render_pattern_png(spec, slot_maps[spec.slot_map], bars, events, png_path, input_midi_tpq)
            png_paths.append(png_path)

        # Same proven layout as the reference script: A4 ~300 DPI, 2 x 5.
        a4_w, a4_h = 2480, 3508
        dpi = 300
        cols, rows = 2, 5
        per_page = cols * rows
        margin_side = 120
        title_y = 110
        title_font_size = 60
        title_gap = 28
        margin_top = title_y + title_font_size + title_gap
        margin_bottom = 100
        inner_margin = 24
        image_scale = 0.92
        page_font = choose_font(title_font_size, bold=True)
        footer_font = choose_font(22, bold=False)
        title_text = f"Original MIDI: {input_midi.name}"

        usable_w = a4_w - 2 * margin_side - (cols - 1) * inner_margin
        usable_h = a4_h - margin_top - margin_bottom - (rows - 1) * inner_margin
        slot_w = usable_w // cols
        slot_h = usable_h // rows
        page_count = max(1, math.ceil(len(png_paths) / per_page))
        pages: List[Image.Image] = []

        for page_index in range(page_count):
            page = Image.new("RGB", (a4_w, a4_h), "white")
            draw = ImageDraw.Draw(page)
            bbox = draw.textbbox((0, 0), title_text, font=page_font)
            title_w = bbox[2] - bbox[0]
            draw.text(((a4_w - title_w) // 2, title_y), title_text, fill="black", font=page_font)

            chunk = png_paths[page_index * per_page : (page_index + 1) * per_page]
            for local_index, png_path in enumerate(chunk):
                row = local_index // cols
                col = local_index % cols
                image = Image.open(png_path).convert("RGB")
                base_scale = min(slot_w / image.width, slot_h / image.height)
                scale = base_scale * image_scale
                new_size = (max(1, int(image.width * scale)), max(1, int(image.height * scale)))
                image = image.resize(new_size, Image.LANCZOS)
                x0 = margin_side + col * (slot_w + inner_margin)
                y0 = margin_top + row * (slot_h + inner_margin)
                x = x0 + (slot_w - image.width) // 2
                y = y0 + (slot_h - image.height) // 2
                page.paste(image, (x, y))

            footer = f"Page {page_index + 1} of {page_count}"
            footer_box = draw.textbbox((0, 0), footer, font=footer_font)
            draw.text(((a4_w - (footer_box[2] - footer_box[0])) // 2, a4_h - 65), footer, fill=(80, 80, 80), font=footer_font)
            pages.append(page)

        raw_pdf = tmp_dir / "catalog_raw.pdf"
        first, *rest = pages
        first.save(raw_pdf, save_all=True, append_images=rest, resolution=dpi)

        gs_exe = None if no_ghostscript else find_ghostscript_executable()
        if gs_exe:
            gs_pdf = tmp_dir / "catalog_a4.pdf"
            if convert_pdf_to_a4_with_ghostscript(gs_exe, raw_pdf, gs_pdf):
                shutil.copy2(gs_pdf, final_pdf)
            else:
                print("[WARN] Ghostscript conversion failed; keeping Pillow-generated PDF.")
                shutil.copy2(raw_pdf, final_pdf)
        else:
            if not no_ghostscript:
                print("[WARN] Ghostscript not found in PATH; keeping Pillow-generated PDF.")
            shutil.copy2(raw_pdf, final_pdf)

        if keep_png:
            png_dir = final_pdf.with_name(final_pdf.stem + "_png")
            if png_dir.exists() and not overwrite:
                fail(f"PNG directory already exists: {png_dir} (use --overwrite)")
            png_dir.mkdir(parents=True, exist_ok=True)
            for png_path in png_paths:
                shutil.copy2(png_path, png_dir / png_path.name)
            print(f"[PDF] Kept pattern PNGs: {png_dir}")

    return page_count


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog=SCRIPT_NAME,
        description="Split PatternLab-selected CH10 MIDI ranges and/or create an A4 2-column PDF catalog.",
    )
    parser.add_argument("input_midi", type=Path, help="Original MIDI file (SMF Type 0 or 1)")
    parser.add_argument("pattern_csv", type=Path, help="CSV downloaded from ADC PatternLab")
    parser.add_argument("--split", action="store_true", help="Save one NAME.MID file per EXPORT=YES row")
    parser.add_argument("--pdf", action="store_true", help="Create a multi-page A4 pattern-grid PDF")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Directory for split MIDI files (default: <CSV directory>/split-midi)",
    )
    parser.add_argument(
        "--pdf-output",
        type=Path,
        default=None,
        help="PDF output path (default: <CSV directory>/<MIDI stem>_patterns.pdf)",
    )
    parser.add_argument(
        "--slot-maps",
        type=Path,
        default=None,
        help="slot_map_definitions.json (default: beside this script)",
    )
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing outputs")
    parser.add_argument("--keep-png", action="store_true", help="Keep per-pattern grid PNG files beside the PDF")
    parser.add_argument("--no-ghostscript", action="store_true", help="Do not run Ghostscript even if found")
    parser.add_argument("--dry-run", action="store_true", help="Validate and print the plan without writing files")
    parser.add_argument("--version", action="version", version=VERSION_TEXT)
    args = parser.parse_args(argv)
    if not args.split and not args.pdf:
        parser.error("select at least one output: --split and/or --pdf")
    return args


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    if not args.input_midi.is_file():
        fail(f"MIDI file not found: {args.input_midi}")
    if not args.pattern_csv.is_file():
        fail(f"CSV file not found: {args.pattern_csv}")

    slot_map_path = args.slot_maps or Path(__file__).with_name("slot_map_definitions.json")
    slot_maps = load_slot_maps(slot_map_path)
    specs = load_pattern_csv(args.pattern_csv)

    try:
        mid = MidiFile(str(args.input_midi))
    except Exception as exc:
        fail(f"cannot read MIDI {args.input_midi}: {exc}")
    if mid.type not in (0, 1):
        fail(f"only SMF Type 0 or 1 is supported, got Type {mid.type}")

    events = merged_absolute_events(mid)
    total_tick = max((event.tick for event in events), default=0)
    bars = build_bar_map(mid.ticks_per_beat, collect_time_signatures(events), total_tick)
    selected = validate_specs(specs, args.input_midi, slot_maps, bars, events)

    output_dir = args.output_dir or args.pattern_csv.parent / "split-midi"
    pdf_output = args.pdf_output or args.pattern_csv.parent / f"{safe_output_stem(args.input_midi.stem)}_patterns.pdf"

    print(VERSION_TEXT)
    print(f"[OK] MIDI       : {args.input_midi}")
    print(f"[OK] CSV        : {args.pattern_csv}")
    print(f"[OK] SLOT_MAPS  : {slot_map_path}")
    print(f"[OK] MIDI type  : {mid.type}")
    print(f"[OK] TPQ        : {mid.ticks_per_beat}")
    print(f"[OK] bars       : {len(bars)}")
    print(f"[OK] export rows: {len(selected)}")

    if args.split:
        print(f"[PLAN] split MIDI -> {output_dir}")
        for spec in selected:
            print(f"       {spec.name}.MID <- bars {spec.start_bar}-{spec.end_bar}")
    if args.pdf:
        print(f"[PLAN] PDF -> {pdf_output}")

    if args.dry_run:
        print("[DRY RUN] Validation completed; no files were written.")
        return 0

    split_count = 0
    if args.split:
        output_dir.mkdir(parents=True, exist_ok=True)
        conflicts = [output_dir / f"{spec.name}.MID" for spec in selected if (output_dir / f"{spec.name}.MID").exists()]
        if conflicts and not args.overwrite:
            fail(f"split MIDI output already exists: {conflicts[0]} (use --overwrite)")
        for spec in selected:
            output_path = output_dir / f"{spec.name}.MID"
            save_segment_midi(spec, output_path, mid, bars, events)
            split_count += 1
            print(f"[SPLIT] {output_path.name} <- bars {spec.start_bar}-{spec.end_bar}")

    pdf_pages = 0
    if args.pdf:
        pdf_pages = create_pdf_catalog(
            selected,
            slot_maps,
            bars,
            events,
            args.input_midi,
            mid.ticks_per_beat,
            pdf_output,
            keep_png=args.keep_png,
            no_ghostscript=args.no_ghostscript,
            overwrite=args.overwrite,
        )
        print(f"[PDF] {pdf_output} <- {len(selected)} patterns, {pdf_pages} page(s)")

    print(f"[DONE] split MIDI: {split_count}")
    print(f"[DONE] PDF pages : {pdf_pages}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
